spring.application.name=Lost_And_Found
spring.datasource.url=jdbc:postgresql://ep-weathered-river-anjev0v4-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uh0Q5zxbftsI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true
cloudinary.cloud-name=dmigul3rr
cloudinary.api-key=221511498496679
cloudinary.api-secret=Y-6tMOfpdj99JhAsmB0QIG7k9R0
cloudinary.upload-folder=lost-and-found
